# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "朱晗"

# URL
baseurl:            ""
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           rdiscount

# Navigation
nav:
  - name:           "关于"
    href:           "/about"
#  - name:           "Download"
    #href:           "//github.com/gfjaru/Kiko/releases"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
